### PR TITLE
How to recompile Reach RTK receiver source code

### PR DESCRIPTION
**Pull request by amilcarlucas**
This information is missing IMHO

### CODE REVIEW

**Comment by amilcarlucas** [comment]
Of course you should add a disclamer saying:
Do this at your own risk, Emlid does not provide support for users that do this, and Emlid is not responsible for any side effects.

Or something like that. I did not add that.

**Comment by ivereninov** [comment]
Thank you for documenting this, but I really do not think that instructions on how to recompile source code belong in the Ardupilot integration. This could create a wrong impression that it is a required step. I think that it is enough to have this on the forum as this is rarely need.

Thanks!

**Comment by amilcarlucas** [comment]
I know that, but I do not know how to add a new page and how to add that new tutorial page to the index. I left that exercise to you guys :)

I still think that it belongs in the user manual, in the tutorials section.

**Comment by amilcarlucas** [comment]
Can you comment on what I wrote ?

**Comment by amilcarlucas** [comment]
Can you add this as a separated new page on the user manual, please ?

**Pull request closed without merging**
